image: ruby:latest

variables:
  JEKYLL_ENV: production
pages:
  stage: deploy
  script:
  - gem install jekyll
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master